language: python
sudo: false
os:
  - linux
cache:
  pip: true
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "nightly"
install:
#  - pip install coveralls
  - pip install .
script:
  - flake8 . --ignore=E501 --select=B,C,E,F,W,T4,B9 --exclude=docs,build
  - pytest 
# after_success:
#  - coveralls
